// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYadyrQLXyLL976tukTRmZ8gCUhxEzzdc',
    appId: '1:461648827529:web:45302c459fd452d174e258',
    messagingSenderId: '461648827529',
    projectId: 'futbol-match-1ec02',
    authDomain: 'futbol-match-1ec02.firebaseapp.com',
    storageBucket: 'futbol-match-1ec02.appspot.com',
    measurementId: 'G-2CJXM6D32Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnJTAqh8IZ0nzn7p37JFp0Dw4gH7iicso',
    appId: '1:461648827529:android:83b869667d7216a974e258',
    messagingSenderId: '461648827529',
    projectId: 'futbol-match-1ec02',
    storageBucket: 'futbol-match-1ec02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU3CG6mZ5hSW_zjGVSRkm7Sq9RH1Ksb_A',
    appId: '1:461648827529:ios:8d4937dc20d03eb074e258',
    messagingSenderId: '461648827529',
    projectId: 'futbol-match-1ec02',
    storageBucket: 'futbol-match-1ec02.appspot.com',
    iosClientId:
        '461648827529-vvhjsfpoaa1k6bc2t20vu70rvnivqign.apps.googleusercontent.com',
    iosBundleId: 'ios.futbol.match.app',
  );
}
